name: Deploy to GitHub Pages
on:
  push:
    branches:
      - hugo
  workflow_dispatch:
  workflow_call:
permissions: read-all
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Checkout note
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: huangyinhaow/note
          path: note
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Move content
        working-directory: note
        run: |
          rm -rf template temp
          mv assets/* ../content
          mv **/*.md ../content
      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.20
        with:
          index: true
          input: content
          output: assets/indices
          root: .
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: publish # deploying branch
          cname: recollect.top
